name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    # Build the Docker image for the frontend-client
      - name: Build frontend-client Docker image
        working-directory: ./frontend-client
        run: |
          docker build -t react-app .

    # Build the Docker image for the server
      - name: Build and push api-server image
        working-directory: ./server
        run: |
          docker build -t api-server .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the frontend-client Docker image
      - name: Push frontend-client Docker image
        run: |
          docker push psscoder/task-manager-app:react-app
          docker push psscoder/task-manager-app:api-server
