name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build the Docker image for the frontend-client
      - name: Build frontend-client Docker image
        run: |
          docker build -t react-app:latest -f ./frontend-client/Dockerfile .
      
      # Push the frontend-client Docker image
      - name: Push frontend-client Docker image
        run: |
          docker tag react-app:latest ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

      # Build the Docker image for the server
      - name: Build server Docker image
        run: |
          docker build -t api-server:latest -f ./api-server/Dockerfile .
      
      # Push the server Docker image
      - name: Push server Docker image
        run: |
          docker tag api-server:latest ${{ secrets.DOCKER_USERNAME }}/api-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-server:latest

      # Build the Docker image for MongoDB
      - name: Build MongoDB Docker image
        run: |
          docker pull mongo:3.6.19-xenial
          docker tag mongo:3.6.19-xenial ${{ secrets.DOCKER_USERNAME }}/mongo:3.6.19-xenial

      # Push the MongoDB Docker image
      - name: Push MongoDB Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mongo:3.6.19-xenial
