name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build the Docker image for the frontend-client
      - name: Build frontend-client Docker image
        working-directory: ./frontend-client
        run: |
          docker build -t psscoder/task-manager-app:react-app .

    # Build the Docker image for the server
      - name: Build api-server image
        working-directory: ./server
        run: |
          docker build -t psscoder/task-manager-app:api-server .

      # Build the MongoDB Docker image
      - name: Build MongoDB Docker image
        run: |
          docker pull mongo:3.6.19-xenial
          # Tag the image with the full repository path and tag
          docker tag mongo:3.6.19-xenial psscoder/task-manager-app:3.6.19-xenial
      
      # Push the MongoDB Docker image
      - name: Push MongoDB Docker image
        run: |
          # Push the tagged image to Docker Hub
          docker push psscoder/task-manager-app:3.6.19-xenial

      # Push the frontend-client Docker image
      - name: Push frontend-client and server Docker image
        run: |
          docker push psscoder/task-manager-app:react-app
          docker push psscoder/task-manager-app:api-server
